In [1]:
#SAMPLING A RANDOM SUBSET

sample(1:20, 5)                  #sample 5 numbers from a range of 1 to 20 without repetitions
                                 #default mode is replace=FALSE

sample(1:20, 5, replace=TRUE)    #sample 5 numbers from a range of 1 to 20 with repetitions

[1]  5  4  7 15  8

[1] 18  6  6 17 12

In [ ]:
#ANALYZING TABULAR DATA FROM A WEBSITE!!

carbon <- read.table("https://stat4ds.rwth-aachen.de/data/Carbon.dat", header=TRUE)
carbon

#header=true to keep the variables names in the file

   Nation      CO2
1  Albania     2.0
2  Austria     6.9
3  Belgium     8.3
4  Bosnia      6.2
5  Bulgaria    5.9
6  Croatia     4.0
7  Cyprus      5.3
8  Czech       9.2
9  Denmark     5.9
10 Finland     8.7
11 France      4.6
12 Germany     8.9
13 Greece      6.2
14 Hungary     4.3
15 Ireland     7.3
16 Italy       5.3
17 Latvia      3.5
18 Lithuania   4.4
19 Malta       5.4
20 Montenegro  3.6
21 Netherlands 9.9
22 Norway      9.3
23 Portugal    4.3
24 Romania     3.5
25 Serbia      5.3
26 Slovak      5.7
27 Slovenia    6.2
28 Spain       5.0
29 Sweden      4.5
30 Switzerland 4.3
31 UK          6.5

In [9]:
head(carbon,3) #display the first 3 rows of the data frame

tail(carbon,3) #display the last 3 rows of the data frame

  Nation  CO2
1 Albania 2.0
2 Austria 6.9
3 Belgium 8.3

   Nation      CO2
29 Sweden      4.5
30 Switzerland 4.3
31 UK          6.5

In [ ]:
#EXTRACT DATA FROM THE TABLE
#notice that you can use the $ operator to refer to a specific variable in the data frame

max(carbon$CO2)     #find the maximum value of the CO2 variable

min(carbon$CO2)     #find the minimum value of the CO2 variable

mean(carbon$CO2)    #find the mean value of the CO2 variable

median(carbon$CO2)  #find the median value of the CO2 variable, e.g. the middle value

Mode_compute <- function(x) {
    ux <- unique(x)                           # Get all unique values from x
    
    match_result <- match(x, ux)              # For each element in x, find its position in ux
                                               # Example: if x = c(1,2,1,3,2,2), ux = c(1,2,3)
                                               # match_result = c(1, 2, 1, 3, 2, 2)
    
    freq_table <- tabulate(match_result)      # Count occurrences of each position
                                               # Returns: c(2, 3, 1) meaning: 1 appears 2x, 2 appears 3x, 3 appears 1x
    
    max_position <- which.max(freq_table)     # Find which position has the highest count
                                               # Returns: 2 (because 3 is the max frequency)
    
    mode_value <- ux[max_position]            # Get the actual value at that position
                                               # Returns: ux[2] = 2 (the most frequent value)
    
    return(mode_value)
}

Mode_compute(carbon$CO2)  #find the mode value of the CO2 variable, e.g. the most frequent value

[1] 9.9

[1] 2

[1] 5.819355

[1] 5.4

 [1] 2.0 6.9 8.3 6.2 5.9 4.0 5.3 9.2 8.7 4.6 8.9 4.3 7.3 3.5 4.4 5.4 3.6 9.9 9.3
[20] 5.7 5.0 4.5 6.5